### ISSUE TITLE
Finish Piral CLI Specification v1

### ISSUE THREAD

**Issue by Felix-Indoing** [smapiot/piral#110]
## Description

I didn't find documents about how to bundle a Pilet without the custom CLI tool, although it was mentioned that this is possible using parcel/webpack.

## Background

We are planning to make a plugin system that can bundle frontend (in React) and backend (in Express) code in one package as some kind of distributable plugins, which I think is not possible with the piral-cli tooling, as it is currently for frontend usage only.

**Comment by FlorianRappl** [comment]
Hi, thanks for the reminder about clearing the documentation on this one.

First, using the `piral-cli` programmatically is totally possible. Actually, it was developed lib-first - so the CLI part is just an addition on top. Other applications such as the initializers (e.g., `create-pilet` or `create-piral-instance`) just use `piral-cli` underneath. No `exec` or anything. We directly export the commands such as `buildPilet` with TypeScript declarations.

Second, independent of that should already be sufficient for your use case (I guess it may/should be) we should add a spec for building / transforming pilets. Since the beginning (when we wrote that an implementation in other bundlers, e.g., webpack may be possible) quite a few things changed. It's still possible, but the bar has been raised quite a bit. Things such as bundle splitting, proper resource loading, common shared dependencies, ... just to name a few are all custom tweaks to Parcel and would require an accurate webpack setup, too. Some of our tweaks to Parcel we already released independently of Piral (e.g., `parcel-plugin-externals`), others may be released in the future, too.

Third, maybe it makes sense to also extract the whole Parcel part regarding building pilets in a plugin (that is then actually used by the `piral-cli`). That way one could say "I am not interested in all the goodies the Piral CLI brings - I just want the final step to be done", going for Parcel with this plugin. Not sure about its applicability though - as debugging should be a crucial part of the dev flow and here we also invented/developed quite some things...

Hope that helps! I'll leave the story open as a documentation enhancement - maybe already for 0.10 (partially), but definitely for v1!

Any feedback appreciated! :beers:

**Comment by Felix-Indoing** [comment]
Thank you for the detailed explanation! Glad to know that `piral-cli` can be used programmatically.
I quickly skimmed through the source code and found several patching to the Parcel Bundler class in the `buildPilet` command, I will try some experiments on that.

About the debugging/development process, what I am trying to do is to have two servers running, one for the shell application server (serving frontend and backend logic) and the other is the plugin source watcher (for developing plugin only). Whenever the plugin source code changes, we trigger the bundling process and send bundled files to the application shell server, which will consume them and reload accordingly. This is quite similar to what `debugPilet` command did (If I am not wrong) except the serving server is not the bundling server (Kras). Because we have both frontend and backend code together in the plugin and need to be sent to the shell server altogether. 

I think this approach is (maybe) acceptable for the plugin developers' experiences. (Yes I am mimicking what the old WordPress plugin system did and trying to bring it to the React/Node.JS world)

**Comment by Felix-Indoing** [comment]
Bundling both frontend and backend code sounds wired and not scaling well, but the point here is for the plugin developer to just focus on the separation of feature delivery but not the separation of the technology stack. I think this is quite handy for small-scale teams.

**Comment by FlorianRappl** [comment]
I think this is a great concept and I am eager to see what you achieve here. Let me know if you need some help.

If there is anything to contribute back (either to the core, the CLI - maybe also in form of a plugin?) then much appreciated!

:beers:
