### ISSUE TITLE
Improve Type Declaration Generation

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#116]
# New Feature Proposal

We want to export custom types from the shell to pilets. Currently, no types are being exported.

## Description

As discussed, it would be nice if we could specify one .ts file, which gets used to export types to pilets.

## Background

Having a portal with custom api and other exports like redux actions, selectors, etc., we need a way to export those to the pilet including their types.

**Comment by FlorianRappl** [comment]
Current tasks on this one:

1. Also support `.ts` besides already generated declaration files (`.d.ts`) via on the fly generation
2. Beautify the generated file (potentially implement another approach for this)
3. Allow exporting more from the app shell (right now the specific exports are handled via interface merging, i.e., only via extension to the original APIs / types)
4. Document how to use this mechanism properly

**Comment by FlorianRappl** [comment]
Brief update:

The generation of the d.ts is still in implementation. Right now it can dynamically detect what kind of API was introduced and assemble that on the fly.

Besides the generation of the correct `PiletApi` interface there is, however, a second problem that needs to be solved: What if the app shell also exports functional stuff (1)? Since this is rather an edge case (but a used one), there is also a different (but similar) question: What if the app shell also brings some "dynamic" dependencies only declared via the `getDependencies` (2)?

Now to solve (1) we initially thought of two potential ways:

- 1.1: export from app shell => generate d.ts and expose as shared dependency
- 1.2: export via special option (e.g., called `shellExports`) => generate d.ts and expose as shared dependency (getDependencies shortcut)

For 1.1 that would have looked close to

```ts
// in app shell entry point
renderInstance(...);
export {  myFunction1, myFunction2 };

// in Pilet
import { myFunction1 } from 'app-shell';
```

We would have required some magic to circumvent the circular dependency and we would have needed to detect the `export` from the app shell entry point.

For 1.2 it could have looked:

```ts
// in app shell entry point
renderInstance({
  // ...
  shellExports: { myFunction1, myFunction2 },
});
```

Usage in pilets as above.

However, both ways do not include a proper answer for (2), so we will now go for something else.

We'll look at the `package.json` of the app shell. If it has a `typings` field we'll include this. Things that are directly exported there will be included in the module declaration of the app shell, otherwise, we'll include anything that is inside its own `declare module` block as-is. As such one is flexible.

As a consequene the way to self-export from the app shell will not be changed. It still needs to be done via a low-level customization over the `getDependencies()` option.

**Comment by FlorianRappl** [comment]
This is available in the preview (`@next`) and in `develop`.
