### ISSUE TITLE
Directly Support Mono Repo Usage

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#143]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Right now the "classic" usage of Piral is a setup of either

- one repo for the app shell
- one repo for each pilet
- distribution of the app shell via NPM registry or share

or

- one repo for the app shell
- a single repo for all pilets
- distribution of the app shell via NPM registry or share

or a combination of the two.

We don't support:

- a single repo for the app shell
- all pilets in the same repo as the app shell
- no distribution of the app shell required

## Background

To achieve the described use case right now the following approach could be followed:

- have a post-build step after piral build of the app shell
- unpack the tgz / its package folder
- move the package folder (i.e., rooted at the unpacked package.json) to the workspace node_modules
- now from Node's point of view its just there

This is rather cumbersome. In the simplest case it should be possible to just "link" against the folder where the "raw" app shell is placed. The Piral CLI should recognize this and *just* work with it.

## Discussion

If some pilets should be placed in other repos the classic model still should be followed. So a mix is totally possible.

As a side-effect it would be also possible to just "npm pack" the raw app shell. It would just work, too. So the emulator package is just another (more optimized) way.

**Comment by tsukhu** [comment]
Few more additions to the requirement

The advantage of a mono repo is when we are able to take care of the dependencies seamlessly so that a change in one dependent package and trigger a build in the client package or sub project.

A common scenario while developing a solution using piral and in a mono repo structure will be
1) Create piral API extensions as sub project
2) Create a piral instance / shell app that depends on the extensions 
3) Create pilet which depend on the piral instance and use the extensions

Currently if I have to make a change in the piral API extension and see its effect in the pilet I need to
1) Build the API extension
2) Update the piral instance with the updated API extension
3) Build the piral instance with a new version
4) Update the pilets with the new piral instance and then see the affect

So I guess the issue is also related to extensions as well as the core piral instance dependencies

**Comment by tsukhu** [comment]
One more item more for documentation is related to any piral-api extensions which you install . For example the dotenv extension you added `piral-cli-dotenv`. We need to have nohoist set at the root level so that the `piral-cli-dotenv` dependency is appropriately installed.

1) At the root of the mono repo in `package.json`
```
  "workspaces": {
    "packages": ["packages/*"],
    "nohoist": ["**/piral-cli-dotenv","**/piral-cli-dotenv/**"]
  },
```
2) Then assuming you have a package called "my-app" as the piral instance . In the package.json of that we can add the dependency as usual for example: 
```
    "piral-cli": "^0.10.0",
    "piral-cli-dotenv": "^0.1.0",
```

**Comment by FlorianRappl** [comment]
> One more item more for documentation is related to any piral-api extensions which you install . For example the dotenv extension you added piral-cli-dotenv. We need to have nohoist set at the root level so that the piral-cli-dotenv dependency is appropriately installed.

I see this rather as an improvement for the plugin resolution of the Piral CLI (i.e., a separate issue).

Ideally, the described process is unnecessary.

Regarding the process described above: Updates to the Piral instance will be shipped instantly in the new way. If you need to rebuild first when extensions change is up to you. For instance, if your `package.json` of the packages contained in the monorepo have "main" specified as `lib/index.js` and require `tsc` for building you'd need to either watch them or rebuild. If you point them to `src/index.ts` even that would just work.

That's at least how this works in our mono repo.

So the only thing we add on top is detection if we are in "raw" or "emulator" mode. If we are in raw mode we'll start a `piral debug` (kind-of) process of the app shell under the hood and wire the two together.

That's at least the current plan.

Hope that makes sense!

**Comment by tsukhu** [comment]
Agreed . Infact I also realized the same regarding the extension api projects. Thank you @FlorianRappl

**Comment by tsukhu** [comment]
I just changed the repo "main" to `src/index.ts` for the api extension projects as you mentions @FlorianRappl and it works fine. So please ignore my earlier comment regarding the extension sub projects .

**Comment by FlorianRappl** [comment]
> I just changed the repo "main" to src/index.ts for the api extension projects as you mention @FlorianRappl and it works fine

Awesome, glad it works! Also no problem - always good to figure these things out together.

**Comment by carvinlo** [comment]
I am using Mono Repo (lerna) to develop a pilet, It is perfet that if the app shell changes, then refresh。

**Comment by carvinlo** [comment]
Now is when I change the app shell code, must be restarted to update

**Comment by FlorianRappl** [comment]
@carvinlo - yes this is indeed the case. We only compile the app shell once, but watch the pilet code for changes. If you want this behavior to be changed then please open a new feature issue -> we will include it in our release train with one of the upcoming versions!

Thanks!
