### ISSUE TITLE
Use socket.io within piral

### ISSUE THREAD

**Issue by chrise-nupis** [smapiot/piral#160]
# Bug Report

I tried to register a pilet with imported socket.io lib, but it does not appear in the menu of the piral instance. I got following error message in chrome browser:
```
dependency.js:31 Error while evaluating my-pilet. TypeError: Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined
    at Object.parcelRequire.../node_modules/buffer/index.js.base64-js (VM17 index.js:40)
    at f (VM16 index.js:4)
    at p (VM16 index.js:4)
    at Object.parcelRequire.../node_modules/socket.io-client/node_modules/socket.io-parser/is-buffer.js.buffer (VM17 index.js:42)
    at f (VM16 index.js:4)
    at p (VM16 index.js:4)
    at Object.parcelRequire.../node_modules/socket.io-client/node_modules/socket.io-parser/binary.js.isarray (VM17 index.js:45)
    at f (VM16 index.js:4)
    at p (VM16 index.js:4)
    at Object.parcelRequire.../node_modules/socket.io-client/node_modules/socket.io-parser/index.js.debug (VM17 index.js:47)
```

## Prerequisites

- see my demo repos: 
- https://github.com/chrise-nupis/piral-instance-demo
- https://github.com/chrise-nupis/pilet-demo

## Environment Details and Version

- Package Version: 0.9.9
- OS: Windows 10
- Browser: Chrome

## Steps to Reproduce

- just run the pilet in debug mode

## Expected behavior

I would like to use socket.io in my pilets.

## Actual behavior

Error while executing the pilet.
Same issue when i use the lib https://github.com/badgateway/ketting.

**Comment by FlorianRappl** [comment]
This is actually a Parcel issue.

See https://github.com/parcel-bundler/parcel/issues/2833.

Figuring out how to circumvent - if at all (issue is that unsupported script types are included within the bundling).

**Comment by lamson** [comment]
I have run into this issue... took me a while to track it down.

The issue occurred when a library dependency had usages of 'global' object - causing SOME_FIELD of undefined because 'global' is undefined.
In my case, it's the 'buffer' v4.x.x library.

To fix this specific `buffer` issue, I added this to my package.json to resolve buffer library to use v5.x.x which doesn't have access to global object.
 
 "resolutions": {
    "**/buffer": "^5.0.0"
  },

You can do something similar to workaround this issue.

**Comment by FlorianRappl** [comment]
I have also tracked it down to use of `global`. I am currently looking into how to teach Parcel that `global` should be preserved.

For some reason it does create `var f = arguments[3]`, where `global` is renamed to `f` in the minification.

**Comment by FlorianRappl** [comment]
Alright, so we will patch this *particular case* together with the package optimization.

There is, unfortunately, not really a chance of making this patch generic (at least to me). Parcel uses an older version of Babel and there the behavior is fixed as seen.

**Comment by lamson** [comment]
I just ran into another case this morning, reference of `global` in `has-symbols` package

See https://github.com/inspect-js/has-symbols/blob/cb9f0a521a3a1790f1064d437edd33bb6c3d6af0/index.js#L3

**Comment by FlorianRappl** [comment]
Alright I'll also include `has-symbols`.

**Comment by chrise-nupis** [comment]
In the other lib that i mentioned (https://github.com/badgateway/ketting) also the use of global.
See https://github.com/badgateway/ketting/blob/master/src/utils/fetch-polyfill.ts#L9
and https://github.com/badgateway/ketting/blob/master/src/utils/fetch-helper.ts#L37

**Comment by FlorianRappl** [comment]
Included :)!

**Comment by FlorianRappl** [comment]
Actually, even though this landed in `0.10.6` we missed a crucial problem with fixing `has-symbols`. It is also used in Node.

This problem may be apparent in the other modules, too - so we'll need a slightly different way of patching.

**Comment by lamson** [comment]
Should we create a separate issue to track this `parcel` bug?
I think there will be more libraries that we need to include in the `patchMap`, or we need a generic solution for all libs, or look at parcel v2?

**Comment by FlorianRappl** [comment]
We will switch to Parcel v2 once its ready / mature enough.

Regarding this issue I don't think Piral is the right place. You could open an issue at Parcel's repo, but I fear it will not change anything.

Actually, the right place to post such issues would be the respective libs. After all, its a problem of the used library that it uses things such as `global`, which are not defined for use in the browser.

As far as workarounds are concerned - you can either post such requests here as an enhancement / feature request, or in the channel. We'll cover what is possible!

**Comment by lamson** [comment]
I agree `piral` is not the right place to solve this issue. I also think it's not good use of time for `piral` team to help patch them libraries. Do you have a suggestion of how the app developer themselves can patch these libs when they run into it, instead of waiting for the next versions of `piral`?

**Comment by FlorianRappl** [comment]
Well, there are a couple of ways. Imho the two most relevant ways are:

- Add a script that runs before building or after `npm install` to modify relevant packages
- Similar, but instead of modifying relevant packages just add / change the Piral CLI

Potentially, the latter should be also possible to adjust / configure from Piral CLI plugins. This way such modifications could be rolled out independently and picked up automatically.

What's your idea here @lamson ?

**Comment by lamson** [comment]
Thanks for the suggestion. I don't have a good solution, mainly just want to bring it up for discussion. 

Both of your options seems good. I think I'm leaning toward the former with additional how-to instructions for the workaround. I feel like it should be the app responsibility to know there is this issue in `parcel`, and know how to workaround it whether they're using `piral-cli` or not.
