### ISSUE TITLE
Approach to dependency isolation in modular app

### ISSUE THREAD

**Issue by eddiesholl** [smapiot/piral#19]
# New Feature Proposal

I'm curious what your thoughts are in piral around how dependencies are managed in the core of the app vs in individual pilet bundles. I've been hunting around this year for a solution to help a large modular front end app ship individual pieces independently, and piral overlaps on heaps of requirements I have.

## Description

I've got lots of questions I'm keen to find out more details for, but initially I'm curious what the plan would be for checking the presence of dependencies. Do the individual modules/pilets operate with no assumptions about npm packages that may have been bundled by the core app? For example, I'm guessing something like react router is bundled in the core app, can a pilet make any assumptions about what dependencies might already be bundled and in scope?

Does the individual pilet get built in a context where it compiles against a specific version of the core app?

Dependency isolation is nice because it allows individual modules to ship at their own pace, but has the down side that no assumptions can be made, and each module needs to bundle its own dependencies, which will be wasteful.

## Background

The general context is I'm hunting for a solution where a team that ships a particular module is free to continuously ship their piece, with minimal bottlenecks and constraints on any other piece, even avoiding a need to redeploy a central app at all.

But with this level of isolation, do you end up with n versions of standard dependencies for n pilets?

Super keen to find out some more about concepts like this, I really haven't come across another project that seems to target this specific problem in this way 👍

**Comment by FlorianRappl** [comment]
Hi @eddiesholl thanks for initiating this (really important) discussion.

### What is possible right now with Piral?

Right now sharing dependencies can be done either by

* having the dependency bundled in the shell ("Piral instance") and as a peer dependency (not bundled, only referenced) in pilets, or
* using the loader at runtime referencing the same URLs (https://example.com/mydepv1.js) from multiple pilets; this could be done implicitly via bundle splitting at compile-time.

Way 1 has certainly some big drawbacks (e.g., updates to the Piral instance may break pilets / potentially without knowing initially if no governance is performed...), while way 2 is really sensitive how bundle splitting is performed.

### What other possibilities exist?

`react-arbiter` (loader package that we use) also supports the notion of resolving common dependencies upfront (before evaluating a pilet). One can think of it as way 1 without specifying the dependency inside the core.

The problem with this approach is two-fold:

* The dependency (e.g., the piral service delivering the pilet information to the client) must deliver an additional field "dependencies" with names of the dependencies as used in the respective bundle / pilet and the URLs for these dependencies.
* The dependencies have to be known with the same URL, as such pilet 1 and pilet 2 (both referencing dependency A) must resolve the dependency A with the same URL. Otherwise, the dependency is still loaded twice.

### How do we want to proceed?

We currently have the following plans:

1. We will soon start working on an additional library called something like "lib pilet"; which is a helper library that helps with governance of pilets, e.g., for checking conformance to a certain Piral instance. This way outdated dependencies (way 1) can be automatically retrieved. This library will also be able, e.g., to find what URLs are registered by pilets, what tiles, ... - all things that may be helpful also for showing information in the FE (e.g., what if a page is requested and cannot be found / it may only be a 404 because the user does not have the rights / some pilets are not loaded).
2. We will try to come up with a way in the Piral CLI to manage common dependencies. Potentially, this will be governed via the Piral service (we are currently working on an API specification for this service).

What are your thoughts? Any other good ideas or suggestions?

**Comment by eddiesholl** [comment]
Thanks for the detailed response. I'm starting to see some basic conceptual tradeoffs, that probably need to be matched to the particular needs of each front end app. In short:
- single compilation phase with full insight into all dependencies, vs
- decoupled builds of individual modules, that are then composed

Another spectrum of choice is:
- smart dependency management for things like dedupeing, incremental downloads as deps are needed, vs
- just bundle each pilet with its dependencies

These basic tradeoffs are basically strict vs decoupled. Stricter models give you more efficient bundles but require more tooling, and probably more coupling of dev teams. More freedom unblocks dev teams, but probably means more duplicated dependencies.

Trying to decouple teams/pilets but keep smart dependencies basically means you are implementing npm in the browser. For example:
> The dependency (e.g., the piral service delivering the pilet information to the client) must deliver an additional field "dependencies"

They also relate to optimising for developer vs end user experience.

Thanks again for your feedback. I'm sure I'll have some more questions once we get a Piral PoC up and running 👍

**Comment by FlorianRappl** [comment]
Yep, the npm in the browser comment is great; this is exactly what we want to avoid. For this reason, the `dependencies` fields is shallow only, i.e., the used dependency has to be self-sustained (there is no other metadata fetched for this dependency, only the dependency itself). In principle one could, of course, build a transitive system, however, potential download times could explode leading to the worst possible UX.

The mentioned trade-offs are true. We usually aim for the decoupled mode, however, that brings us to the requirement of really good tooling. For the portal we've build we usually followed the path of guidelines for each team implementing such pilets; guidelines that involved a basic process for dependencies such as "bundle it with your pilet". A central governance would "see" (via the repos / some additional tooling) the common dependencies and decide how to handle it.

In the next days / weeks we will extend our documentation a bit (and refine many of the rough edges right now) to get a set of recommendations / guidelines / discussion starters out there.

Any contribution much welcome and appreciated :beers:!

**Comment by eddiesholl** [comment]
Just discovered the internals of `react-arbiter`, very interesting 😄

**Comment by eddiesholl** [comment]
I've been looking at building a POC. It looks like all of the feed examples are offline. That would be one useful thing to get up and running again, to get a feel for what a feed data source and implementation would look like.

I think we're looking at making a few different tradeoffs that don't quite match with the exact choices made in Piral so far, but there's still a huge amount of overlap with the research and initial work we've done 👍

**Comment by FlorianRappl** [comment]
Yep we've taken the feed mostly offline for the moment, but we wanted to activate it soon enough. One of the reasons is that right now the feed would only contain 2 sample pilets which could be rather useless and having "your own feed" is what is much better...

We have an internal service that contains many things such as feature flags, SSO and RBAC integrations and much more in the working, but I think we could also open-source a quite simple pilet service that can do publishing and serving of pilets (would be a simple Node.js / express app). If you are (still?) interested in that we can make it available by tomorrow.

Just let me know!

PS: I've created a Gitter chat; we can also easily discuss these things directly if desired! https://gitter.im/piral-io/community

**Comment by eddiesholl** [comment]
The main thing is that I haven't found any specific examples of what the exact feed schema needs to be, although you can kind of reverse engineer it from code inspection. I think that would make it much easier for people to try it out and get something running 👍

The full example implementation is nice but doesn't run because of the missing feed.

**Comment by FlorianRappl** [comment]
For the "simple feed" (using `piral-core`, where you wire everything together as you wish) all you need is some API (that you define), however, if you go for the full `piral` you'll end up with a GraphQL service. Publishing requires a standard HTTP POSTendpoint.

See https://docs.piral.io/specifications/piral-api for the spec of the Piral API.

**Comment by FlorianRappl** [comment]
We've added a sample feed service:

https://github.com/smapiot/sample-pilet-service

**Comment by FlorianRappl** [comment]
With 0.11 this is now closed. Our primary approach will be using import maps (see #124 for details).

This allows to effectively de-duplicate code. It works for external modules as well as own code. Anything that may be shared from one pilet to other pilets should be done via import maps. The application shell does not play any role here.
