### ISSUE TITLE
Add mapped name, value types to PiralStoreDataEvent

### ISSUE THREAD

**Issue by MattShrider** [smapiot/piral#198]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

The SharedData interface on the PiralInstance module can be used to specify the type of data being set based on the key/name. This works for `piletApi.on`, `piletApi.emit`, but it doesn't transfer over to the PiralEventMap's `"store-data"` event.

I believe that it may be possible to use typescript conditional types to copy over the value type from the store-data event, by making `PiralStoreDataEvent` a generic that takes a key, to look like the following: (the `name` and `value` property was changed.
```typescript
  export interface PiralStoreDataEvent<key extends keyof SharedData> {
    /**
     * The name of the item that was stored.
     */
    name: key;
    /**
     * The storage target of the item.
     */
    target: string;
    /**
     * The value that was stored.
     */
    value: SharedData[key] || any;
    /**
     * The owner of the item.
     */
    owner: string;
    /**
     * The expiration of the item.
     */
    expires: number;
  }
```

And the new interface for the EventEmitter would also update: (the `on` property was changed)
```typescript
  /**
   * The emitter for Piral app shell events.
   */
  export interface EventEmitter {
    /**
     * Attaches a new event listener.
     */
    on<K extends keyof PiralEventMap>(type: K, callback: Listener< K extends "store-data" ? PiralStoreDataEvent<K> : PiralEventMap[K]>): EventEmitter;
    /**
     * Detaches an existing event listener.
     */
    off<K extends keyof PiralEventMap>(type: K, callback: Listener<PiralEventMap[K]>): EventEmitter;
    /**
     * Emits a new event with the given type.
     */
    emit<K extends keyof PiralEventMap>(type: K, arg: PiralEventMap[K]): EventEmitter;
  }
```

## Discussion
I'm not sure if my provided theoretical interfaces would work or not.

**Comment by FlorianRappl** [comment]
Sounds good to me - do you want to give it a try?

Any contribution appreciated!

**Comment by MattShrider** [comment]
I'll take a look to see if it is easy to add.

**Comment by MattShrider** [comment]
https://github.com/smapiot/piral/compare/develop...MattShrider:features/%23198-store-data-event

That's about as far as I got on this, I couldn't get the project building correctly and ran out of time to work on it -- didn't want to open a PR because it is untested.

**Comment by FlorianRappl** [comment]
We've added a very simple variant here. Not sure if its enough at this point.

The `on` etc. methods have been untouched (because in general, i.e., from a plugin / non-core Piral code that would be the situation, too). The event args are now generic using `any` by default (i.e., same situation as initially).

The difference is that one can use the interface also with a type. So instead of inferring from something that is - at this point in time - not inferrable (since the shared data is not used together with interface merging) we leave it up to the user to insert the right type.

Why is this still better than beforehand? Instead of declaring the right type somewhere in the handler (or just dealing with `any`) it can now be done upfront. So its a bit better, even though not as ideal as desired or wanted.

I'm still thinking of other ways (obviously interface merging would work here, too - but maybe especially for the given scenario there are other options to available as well).
