### ISSUE TITLE
Add a 3rd argument to registerPage for additional metadata

### ISSUE THREAD

**Issue by janeirikforland** [smapiot/piral#201]
# New Feature Proposal

Add a 3rd argument to registerPage for additional metadata, which could then be used to ex. create a breadcrumb nav. I should be possible to connect a route name with a more friendly display name, and then use both to ex. create a breadcrumb. 

## Description

When registrering pages in a new Pilet, it should also be possible to add a more friendly display name to the route of that registered page, that then would also be added to the state. This could then be used to ex. create a breadcrumb nav. 

## Background

The current solution does not support my goal of creating a breadcrumb nav, not without creating an API extension (ie. createBreadcrumbApi()). 

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by axinom-benjamin** [comment]
I support the idea.
I'm also having to build a breadcrumb in the project that I'm working on and was thinking about an API extension so far. But having a possibility to send additional metadata when registering pages would already help a lot I guess.

A static name alone would not be sufficient for my case though since there are pages where the display name depends on the actual `match` of the route and might even be required to be loaded from a backend API. (e.g. a route like `/asset/:id` might want to load the title of the asset with the given ID from the backend to use in the breadcrumb)

So maybe just adding a generic payload property and then leave it up to the project to make use of it would do the trick already?
