### ISSUE TITLE
Parallel Builds using CRA Break in Monorepo

### ISSUE THREAD

**Issue by EmperorRXF** [smapiot/piral#256]
# Bug Report

## Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
Please clone the repository here - https://github.com/EmperorRXF/PiralBuildError
- [X] Are you running the latest version?
- [X] Did you perform a search in the issues?

## Environment Details and Version
node - 12.17.0
yarn - 1.22.4
lerna - 3.22.1
piral - 0.11.6
react-scripts - 3.4.1

OS - Windows 10 Pro 1909

## Description

When having a monorepo setup (I'm using yarn-workspaces with lerna), and performing a "build" of all packages in parallel, the Piral shell application `build` causes other independent projects which are building to fail (this happens when **create-react-apps** are inside the monorepo and are being built as the same time).

## Steps to Reproduce

1. Clone this repository - https://github.com/EmperorRXF/PiralBuildError
2. Run `yarn`
3. Run `yarn build`

## Expected behavior

I would expect both the CRA package & the Piral application-shell package both to be built successfully.

## Actual behavior

Immediately after the Piral "Bundle Emulator" shows in the console output, the CRA build which is happening in parallel will fail with a message like "Cannot find module %", where the actual module name will differ from each execution.

![Image](https://i.imgur.com/vDyLZrc.png)

## Possible Origin / Solution

I didn't dig too much into this, but have narrowed down the issue to https://github.com/smapiot/piral/blob/7b749bd6b074f1d01bc765dffcf8df521b4e5921/src/tooling/piral-cli/src/common/patcher.ts#L72

It seems during the `patching` process of the root node_modules folder, some packages fail to be found by the `require` call which runs from the parallel builds of the monorepo (the CRA packages). Maybe because piral-cli is calling "**writeJson**" on some package.json at the time it is requested by another package build, and the file is locked?

Once the folder patching process is complete piral-cli creates a ".patched" file to avoid "re-patching", and if the monorepo is rebuilt after the creation of this ".patched" file, then the build error on CRA packages do not occur. In fact to recreate this build error, the root node_modules folder needs to be deleted.

This is proving to be troublesome right now in my project where we're using many CRA packages along with Piral inside a monorepo, and one workaround I'm using is to run the monorepo build in "serial" mode rather than "parallel" which grantees build success. But this pushes back our build times significantly. Any help with fixing this issue is appreciated.

**Comment by FlorianRappl** [comment]
Hi, to identify if its really about the module optimization you could also turn it off.

Example:

```sh
piral build --no-optimize-modules
```

This will turn off the modification of the modules in `node_modules`.

I guess your analysis about the locking is correct, only question is how to avoid it reliably. Maybe someone has a good idea here.

**Comment by EmperorRXF** [comment]
Thank you for the quick response!

Yes having `piral build --optimize-modules false` fixes the build error on parallel builds :) I actually didn't know about this flag before (my bad for not going through all CLI flags)

What would be the downside of not optimizing node_modules folder? I'm not exactly sure of what's happening with this patching process.

**Comment by FlorianRappl** [comment]
There is an issue with Parcel (well, honestly, the problem is with Babel / the used packages) that deals with two things:

1. Sometimes packages are used that assume Node.js -> while webpack configures Babel to change `global` to `window`, Parcel does not do that. So these packages will make your code stop working. We (monkey) patch (a selected list of the most known) packages.
2. How the browserconfig should be used is as follows: A library (package in node_modules) tells Babel what the state of your delivered code is. An application (e.g., your Piral instance) tells Babel what the target of the current code is.

(2) presents a problem. It means that some libs that come with a `.browserconfig` (could be also specified in the package.json) say something like ie11, but are in fact ES6 modules. Now if your app has a browserconfig targetting ie11 then Babel will not transpile the mentioned package as the browserconfig already mentions ie11.

To counteract the previously mentioned scenario we set all dependencies to "node", which means that Babel will transpile them *in any case*.

What does that mean now for your code? If you target only the latest browsers then you should always be fine (i.e., turning it off is actually good!). If you target some specific browsers I would advise you to test in these browsers. If something is not working (e.g., due to use of ES6 syntax) then this call (or something similar) may be needed.

I'm not sure if Webpack handles (2) better than Parcel. You could also give the new (0.11.7) `piral-cli-webpack` a shot. Its an in-place replacement for `piral-cli-parcel`, which is used by default.

**Comment by EmperorRXF** [comment]
Aha I see, yes makes a lot more sense now!

I don't get any 'bright' ideas right now about handling the patching process when there are parallel builds taking place (however I can adjust my monorepo build to always build the piral application-shell as the last package using lerna --scope & --exclude flags).

Also I will give `piral-cli-webpack` a try. You've been very helpful!

**Comment by FlorianRappl** [comment]
With 0.11.8 we switch from Parcel to Webpack as the default bundler.

Furthermore, the `--optimize-modules` flag is by default `false`, i.e., instead of an opt-out via `--no-optimize-modules` you'd opt-in via `--optimize-modules`. Therefore, by default this is not an issue and everyone who opts-in does it on purpose.
