### ISSUE TITLE
Mario5 Sample Pilet Still Being a v0 Pilet

### ISSUE THREAD

**Issue by kpyfan** [smapiot/piral#257]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

`piral-core 0.11.5`
Also seen on https://demo-full.piral.io

Safari Version 12.0.2 (13606.3.4.1.4)

## Description

Pilet assets are attempting to load from a relative URL of the piral instance rather than the pilet URL.

For example, on `demo-full`:

Chrome: 
![image](https://user-images.githubusercontent.com/3434802/85457707-34266300-b555-11ea-8ece-36d0c8348793.png)

Safari:
![image](https://user-images.githubusercontent.com/3434802/85457863-57e9a900-b555-11ea-9b07-525aaf282a61.png)

As you can see, it attempts to load from the `demo-full.piral.io` domain instead of `assets.piral.io`

This results in the following "css":
![image](https://user-images.githubusercontent.com/3434802/85457931-6afc7900-b555-11ea-90d6-516076ae6775.png)

and these console errors:
![image](https://user-images.githubusercontent.com/3434802/85458003-8071a300-b555-11ea-9a99-f9eb6e8bb474.png)

## Steps to Reproduce

1. Access a piral instance in Safari
2. Open Chrome inspector and look at asset loading for pilets

## Expected behavior

Assets should be loaded from the same domain as the feed

## Actual behavior

Assets loaded from piral instance URL instead, resulting in 404s.

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Hi @kpyfan how was the pilet produced? Because the issue seems to be related to v0 pilets.

Your own pilets should all be v1 pilets and thus load fine. Safari has an issue with dynamic setting of base URLs for script evaluations; it needs to have a script tag underneath (which is what v0 provides).

Thanks for noticing that. I'll re-publish the sample pilets!

**Comment by FlorianRappl** [comment]
All done and published.

**Comment by kpyfan** [comment]
@FlorianRappl we're seeing this on a v1 pilet that one of our other teams has produced. Is there any additional info I can provide you from that pilet that might help track this down?

**Comment by FlorianRappl** [comment]
What exactly are you seeing? You need to be specific here because v1 certainly works with referenced resources in all browsers incl. IE11.

**Comment by kpyfan** [comment]
We're seeing the same issue that I referenced above. In Safari, our pilet is loaded from one url (ex: `cdn.company.com/pilets/piletname/0.1.0/package/dist/index.js`), but the css chunks are attempting to be loaded from the url of the Piral instance (ex: `shell.company.com`) instead. I've validated that our pilet _is_ correctly marked as a v1 pilet.

**Comment by FlorianRappl** [comment]
I guess then the problem is *your* feed service. The feed service needs to deliver v1 pilets with the appropriate format.

See [the specification](https://docs.piral.io/reference/specifications/feed-api-specification#core-api-design), in particular the `PiletMetadataV2` interface. The `requireRef` is **required**.
