### ISSUE TITLE
Return disposer from register APIs

### ISSUE THREAD

**Issue by nmalyschkin** [smapiot/piral#336]
# New Feature Proposal

## Description

The idea is, that all register APIs return an unregister function instead of `void`.

```jsx
export function setup(app: PiletApi) {
    const unregisterMenu = app.registerMenu(() => (
        <a href="https://docs.piral.io" target="_blank">
            Documentation
        </a>
    ));

    app.on("someEvent", () => {
        unregisterMenu();
    });
}
```

## Background

While this feature does not give you any additional flexibility, it reminds you that you probably should unregister at some point, advocating best practices.

## Discussion

This could be also applied to the event handler registration via `app.on`. The downside would be, that it wouldn't be possible to chain handler registrations like this, making it a breaking change:
```jsx
app.on("foo", () => {}).on("bar", () => {});
```

**Comment by FlorianRappl** [comment]
> it reminds you that you probably should unregister at some point, advocating best practices.

That is only true in edge cases. In the usual (common) case you will never unregister. Your registrations are valid for the entire lifetime of the pilet, which is active for the lifetime of the application.

> This could be also applied to the event handler registration via app.on.

Yes, we will *never* break the pilet API. We could introduce another function for this, but since its so straight forward

```
function appendFluent(api, name, handler) {
  api.on(name, handler);
  return () => api.off(name, handler);
}
```

I'd rather leave it out. The current `on`, `off` is taking the Node.js EventEmitter approach, which is sufficiently fine imho.

In general this is great and we should introduce this for all `registerX` calls.
