### ISSUE TITLE
Update Piral.Blazor to .net5

### ISSUE THREAD

**Issue by MarioGit1** [smapiot/piral#359]
# New Feature Proposal

Update Piral.Blazor from .NET Core 3.2. to .net5

## Description

Since November 2020 .net5 is released, so when someone uses Pilets with .net5 this won't work.

## Background

We love the idea behind Piral and it fits exactly our needs, but the support for .net5 is essential. Maybe there is a way to simple change the used framework but we didn't find it.

## Discussion

Is it possible to use blazor-pilets with different .net version? I don't think this would work or is there a way to isolate the different webassemblies?

**Comment by FlorianRappl** [comment]
So `piral-blazor` (NPM package) is pretty much independent of this (which .NET runtime you use) choice. It uses `Piral.Blazor` to deliver the core / shared WASM libs.

For `Piral.Blazor` (NuGet package) we offer different versions - starting with the next release the versions will match the corresponding version of Blazor - which matches the target framework (e.g., 3.1 -> .NET Core 3.1, 5.0 -> .NET 5.0 etc.).

Indeed, once you decided for a particular `Piral.Blazor` version then all Blazor pilets need to stick to this .NET version. Theoretically, you could break out of this, however, there is also a JS singleton responsible for Blazor which holds all assemblies. Unfortunately, since this is a singleton it will not work with different versions - even though in general it could. It's one of the bad (but practical) design decisions within Blazor.

I'd leave this issue open here (and not move it into `Piral.Blazor`s repository) until we have .NET 5 released.

**Comment by FlorianRappl** [comment]
Not so fast my little bit ;).

**Comment by FlorianRappl** [comment]
You are making good work stale bot, but this one is just currently being worked on. A bit more patience!

**Comment by FlorianRappl** [comment]
This will be made available in the Piral.Blazor repository. Will be tracked there.
