### ISSUE TITLE
Directly Evaluate "Fixed" / Static Pilets

### ISSUE THREAD

**Issue by iotcloudarchitect** [smapiot/piral#39]
# New Feature Proposal

## Description

Right now already attached pilets are evaluated together with the dynamically loaded pilets. Thus the attached pilets need to wait unnecessary long to be integrated.

## Background

In general pilets should be evaluated as fast as possible. Maybe different strategies should be selectable, where async​ ​​​​​(already introduced) is just one short way.

**Comment by FlorianRappl** [comment]
This has now been fixed with `react-arbiter` v0.9.1 - here we use the progressive strategy.

If `async` is not set rendering will start (as usual) once all modules have been evaluated, otherwise rendering starts when the module metadata has been received. At this point in time though, the fixed / static pilets are already evaluated.

Since the strategy is progressive pilets are also evaluated once available instead of all-at-once.

Landed in `develop`.
