### ISSUE TITLE
App shell not launching due to react-router incompatibility

### ISSUE THREAD

**Issue by mitchjohnson000** [smapiot/piral#441]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version
piral version 0.14.5
Chrome
## Description
Now that react router is in v6. We need to update piral-core to match v6; which no longer exports useRouteMatch, useHistory,  __RouterContext, Switch, StaticRouter, or Redirect. 

Another solution is to change react-router dependency in piral-core to ^5.2.1.

## Steps to Reproduce

1. clear node_modules/ package lock
2. install dependencies
3. run app shell

## Expected behavior
app shell launches and renders

## Actual behavior
Nothing renders

**Comment by FlorianRappl** [comment]
Hm not sure how its a bug. We use `react-router` in v5.

**Comment by mitchjohnson000** [comment]
> Hm not sure how its a bug. We use `react-router` in v5.

Yes, but piral-core will fetch v6.

**Comment by FlorianRappl** [comment]
> Yes, but piral-core will fetch v6.

Actually this is on you. With npm v6 peer dependencies are not installed. Unfortunately, this sane default was changed - now it may be fetched since npm v7.

You are right that we should adopt the peer dependencies, but you should include a specific dependency in your solution, too. That's the idea with `piral-core`. `piral` itself pins that version for instance for you. But with `piral-core` this freedom was left to the developer.

**Comment by mitchjohnson000** [comment]
I understand the issue now, thanks for your help.

**Comment by FlorianRappl** [comment]
Yeah honestly, I think we should address it. Thanks for raising this!
