### ISSUE TITLE
extendSharedDependencies removed in 0.14.0

### ISSUE THREAD

**Issue by hubertglowiak** [smapiot/piral#455]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

0.14.7

extendSharedDependencies has been removed randomly in 0.14.0. Any specific reason why?

**Comment by FlorianRappl** [comment]
Since 0.14 we use SystemJS for the management of shared dependencies; any interaction with the shared dependencies is therefore not done in Piral but within SystemJS.

You can use the [SystemJS API](https://github.com/systemjs/systemjs/blob/main/docs/api.md) to manipulate that set to your needs.

Is that what you've been looking for or is there some use case missing?

**Comment by FlorianRappl** [comment]
Ping @hubertglowiak .

**Comment by hubertglowiak** [comment]
@FlorianRappl thanks for your response. That's what I've been looking for, but nice if it could be documented!

Regards

**Comment by FlorianRappl** [comment]
Yeah we include it in the migration doc. I assigned it to 0.14.8.
