### ISSUE TITLE
Support for Pre-/Post-Scaffolding hooks

### ISSUE THREAD

**Issue by SantoJambit** [smapiot/piral#61]
# New Feature Proposal

It is desired to handle actions before or after the scaffolding takes place.
(for us it's all about the after hook).

## Description

Ideally, it would be possible to execute custom code after scaffolding took place, for example to automatically format files to the desired code-style or maybe to expand template variables in files.

## Background

In our case, the package.json is generated by piral. But we want to have a consistent ordering of attributes in the package.json, which is why we use `npx sort-package-json` to sort it.

## Discussion

- It might also be desirable to prompt the user for some things in order to do the work.
- Should these hooks also be able to run upon upgrade?
- Two ways I can think of:
  - Use a javascript file. In that case, the package.json might need to contain dev-dependencies beforehand and the script might need to remove these dev-dependencies afterwards.
  - Only specify a command to run (string).. for example, if using npx, the required package to execute the code would be automatically downloaded and executed.

**Comment by FlorianRappl** [comment]
Sounds like a great proposal.

Regarding the upgrade - I guess the best way would be to have four hooks:

1. Pre-Scaffold (done after [optionally] creating the directory, but before anything else, e.g., the tsconfig, has been scaffolded)
2. Post-Scaffold (done right before the scaffold command is exited, i.e., after everything has been scaffolded and copied accordingly)
3. Pre-Upgrade (done before anything is touched, i.e., right before the command will start moving things around)
4. Post-Upgrade (done right after the new Piral instance has been added and all files etc. have been touched)

If, e.g., the post-scaffold should be identical to post-upgrade then the user can just set both to the same code. Otherwise, distinguishing between scaffold and upgrade leaves room for flexibility and avoids confusion. Normally, I guess the operations done after a scaffold should not (all) been repeated during upgrade.

Now regarding what is executed / where it is defined I would propose the following:

We still use the `package.json` to define everything regarding scaffolding from the perspective of the Piral instance. We would just extend the `pilets` section:

```json
{
  "pilets": {
    "pre-scaffold": "...",
    "post-scaffold": "...",
    "pre-upgrade": "...",
    "post-upgrade": "..."
  }
}
```

All of them are optional. If they are missing, the hook is not triggered.

Regarding the content the best option is to potentially follow your suggestion number 2 (the command is specified). The dev dependency resolution - especially in the case of a pre-hook where nothing (except the target directory) may exist yet could be to difficult to get right.

Regarding the prompt suggestion - I think I like it. The question is now: What should the default be? We could do:

1. Default = Always prompt before running any hook. There is an option to disable prompting.
2. Default = Never prompt before running any hook. There is an option to enable prompting before running a hook.

What are your thoughts @SantoJambit ? Thanks!

**Comment by SantoJambit** [comment]
I thought of the prompting more like the script would ask the user "enter your feed service url" or something.. I didn't mean it like "do you want to run post-hook xyz?". This doesn't have to be part of the piral cli, although it could (for a consistent user-experience), but I think it would be easier to leave that to the script itself for now.

About the pre-scaffold hook: Not sure if there is actually the need for this. I can't imagine anything you might want to do before scaffolding took place.

**Comment by FlorianRappl** [comment]
I don't understand that part of prompting - if you mean just to fill out, e.g., variables, then this has nothing to do with the hooks (or does it?). I mean any kind of script could prompt.

Note also that the Piral CLI will not use prompts - it will always use CLI parameters. For prompts we will potentially create a NPM Initializer (see, e.g., https://elijahmanor.com/npm-init-initializer/) called `create-pilet`, such that `npm init pilet` can be run. Under the hood it will use the Piral CLI, but it would prompt (either via free text or a selection) the user to make the selections.

I agree that a pre-scaffold does not seem very useful at first, but for symmetry reasons I would include it (plus you never know - I can think of at least 2 potentially useful things to accomplish here).

**Comment by SantoJambit** [comment]
Just ignore the prompting.

The NPM initializer method would be a nice addition to avoid a global install of the piral-cli.

**Comment by FlorianRappl** [comment]
Landed in `develop`.

The used names differ from the proposal - instead of dash-case we use standard camelCase (`postScaffold`, `postUpgrade`, ...) which complies more with *package.json* (see `deveDependencies`).
