### ISSUE TITLE
what happened to React Native?

### ISSUE THREAD

**Issue by cortopy** [smapiot/piral#627]
# New Feature Proposal

I can see from searching in the repo that React Native had a framework package but was removed recently.

However, the [docs](https://github.com/smapiot/piral/blob/a8fda2d21be0fe7b8e1245496bf2a2eb33f82135/docs/tips.md?plain=1#L21)  still mention that it's supported

## Description

I'd just like to know if it was removed because it won't be supported in the foreseeable future

**Comment by FlorianRappl** [comment]
We removed that one with the 1.0.0 as the package was not updated recently and since there was no interest maintaining it was rather pointless.

We plan, however, to bring this (and further things) to life with Piral v2. Here, the idea is that we'll provide rather the basic packages (such as an orchestrator) and are therefore much more flexible in terms of combining / offering framework support.

Hope that helps!
