### ISSUE TITLE
Support Angular.js

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/piral#87]
## Description

Right now we support the top players (React obviously, Angular and Vue), but (except for Hyperapp) we do not support other (established) frameworks.

We should go for integrating a converter to handle Angular.js (i.e., Angular 1 / classic). Like all other converters it would be **opt-in**.

## Background

* Homepage [angularjs.org](https://angularjs.org)
* GitHub [github.com/angular/angular.js](https://github.com/angular/angular.js)

Maybe useful:

* https://softeng.oicr.on.ca/chang_wang/2017/04/17/Using-AngularJS-components-directives-in-React/
* https://stackoverflow.com/questions/18611214/turn-off-url-manipulation-in-angularjs

## Discussion

Right now I can't think of anything to discuss.

**Comment by ximbal** [comment]
This would be "angular" since a lot of us have large (1.X) code bases that would need to coexist with new techs. A classic scenario would be not enough time to rebuild or short time to market. Piral support for Angular 1.X would be an important enabler in both and more important in the adoption of PWA's and the piral model.

**Comment by FlorianRappl** [comment]
Available in the preview.
